### ISSUE TITLE
database error on installing

### ISSUE THREAD

**Issue by azpro-git** [ho-nl/magento2-ReachDigital_Review#1]
Magento 2.2.3 gives Database error on installing the module via command line bin/magento module:enable Ho_Review
On command bin/magento setup:upgrade we have :

Module 'Ho_Review':
Installing data... SQLSTATE[HY000]: General error: 1005 Can't create table `XXXXXXXXXXXXXXXX`.`rating_consideration` (errno: 150 "Foreign key constraint is incorrectly formed"), query was: CREATE TABLE IF NOT EXISTS `rating_consideration` (
  `consideration_id` int UNSIGNED NOT NULL auto_increment COMMENT 'Review consideration id' ,
  `review_id` bigint UNSIGNED NOT NULL COMMENT 'Review id' ,
  `type` smallint NOT NULL default '0' COMMENT 'Type' ,
  `value` text NOT NULL COMMENT 'Value' ,
  PRIMARY KEY (`consideration_id`),
  INDEX `REVIEW_DETAIL_REVIEW_ID_TYPE` (`review_id`, `type`),
  CONSTRAINT `RATING_CONSIDERATION_REVIEW_ID_REVIEW_REVIEW_ID` FOREIGN KEY (`review_id`) REFERENCES `review` (`review_id`) ON DELETE CASCADE
) COMMENT='Review considerations' ENGINE=INNODB charset=utf8 COLLATE=utf8_general_ci

Thanks!

**Comment by Jeroenll** [comment]
Hi @azpro-git,

I've not managed to reproduce this (yet) but made some improvements to the install script. Can you test out the develop branch? What does MySQL say if you directly create the table?

**Comment by azpro-git** [comment]
Ha Jeroen,

Ik zal het vanavond even opnieuw proberen. Kan dev ook geinstalleerd worden
via SSH command?

Ter info - ik kon niet verwijderen/uninstall script draaien via SSH.
Melding dat niet is geïnstalleerd via composer.  Kon wel module disablen en
daarna via Magento Setup Module Manager uninstall script draaien. Denk je
dat ik dan nog DB table - DB entries - Files op server handmatig moet
verwijderen?

Dank!

**Comment by Jeroenll** [comment]
Er is zo te zien geen tabel aangemaakt dus met `composer remove reach-digital/magento2-review` wordt de module weer verwijderd. Gebruik vervolgens `composer require reach-digital/magento2-review dev-develop` om die branch te gebruiken.
